language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package publishOnlyWhenOnMaster
scala:
  - 2.11.0
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
    - denys.shabalin@typesafe.com
env:
  global:
   - SCALAMACROS_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAMACROS_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "NrlhQzFIivfkBviwz2BM4+Vc8NK+iQfDgtZLmBKWt60YOTjLRJ8dDcEHmTq4zpnATT5vfA75JN9OqTDS2TUgrfJ0BE6oHr1AuHD6OzU7KzFobWR0k6u/gKUTOFqmqM+f066EKnam8mLTSr4jAD37D+yFgaHu1s38LgaHfaaip0U="
   - secure: "w712Edbh3kb5nKvgxp82yp6QyMMw4E8N3pIDA56EQQqiWvy+DALAix1akr/lBPmgYQ1LnwPqLO9Zri/YojOkK0O+HUtC013tPlvi5x7foJQJAMPup6ShsQ9FxU5L9XrmkjCHmxrd0B5uYG22vTb+2UbYlR21C0Z8clEfn9ixBbM="
